import { useAuth0 } from '@auth0/auth0-react'
import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { Game } from '../components/page/game'
import { Loading } from '../components/page/loading'
import { Login } from '../components/page/login'
import { Container } from '../components/page/page'
const Home: NextPage = () => {
  const { isAuthenticated, isLoading } = useAuth0()
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading ? <Loading /> : isAuthenticated ? <Game /> : <Login />}
    </Container>
  )
}
export default Home
