import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useCallback, useRef, useState } from 'react'
import { BoardOrigin } from '../components/board/boardOrigin'
import { DifficultySelector } from '../components/difficultySelector/difficultySelector'
import { HighScoreModal } from '../components/highscoreModal/highScoreModal'
import { Container, Main } from '../components/page'
import { BoardSize, Difficulty, DifficultyFirstStates, Pos } from '../types/type'
import { createBom } from '../utils/bom'
import { DIFFICULTY_SPECIAL } from '../utils/constants/difficulty'
import { FIRST_STATE_COMMON, FIRST_STATE_EASY } from '../utils/constants/firstState'
import { saveCompletedResult } from '../utils/result'

const Home: NextPage = () => {
  if (typeof document !== 'undefined') document.oncontextmenu = () => false

  const [currentFirstState, setCurrentFirstState] =
    useState<DifficultyFirstStates>(FIRST_STATE_EASY)

  const refreshStateWithDifficulty = (values: DifficultyFirstStates) => {
    refreshStateCommon()
    setCurrentFirstState(values)
    setBoardSize({ sizeX: values.sizeX, sizeY: values.sizeY })
    setBoard(values.board)
    setBoms(createBom(values.bomNum, values.sizeX, values.sizeY))
  }

  const refreshState = () => {
    refreshStateCommon()
    setBoardSize({ sizeX: currentFirstState.sizeX, sizeY: currentFirstState.sizeY })
    setBoard(currentFirstState.board)
    setBoms(createBom(currentFirstState.bomNum, currentFirstState.sizeX, currentFirstState.sizeY))
  }

  const refreshStateCommon = () => {
    setGameState(FIRST_STATE_COMMON.gameState)
    setFlgPosition(FIRST_STATE_COMMON.flgPosition)
    setCount(FIRST_STATE_COMMON.count)
    setPushedBlockNum(0)
    countStop()
  }
  //-1:PreStart, 0:Normal, 1:Completed, 99:Gameover
  const [gameState, setGameState] = useState(FIRST_STATE_COMMON.gameState)

  // -1:爆弾, 1-8:クリック済み, 9:未クリック, 99:フラグ, 100: ?
  const [board, setBoard] = useState(currentFirstState.board)
  const [flgPosition, setFlgPosition] = useState<Pos[]>(FIRST_STATE_COMMON.flgPosition)
  const [count, setCount] = useState(FIRST_STATE_COMMON.count)
  const [boms, setBoms] = useState(
    createBom(currentFirstState.bomNum, currentFirstState.sizeX, currentFirstState.sizeY)
  )
  const [pushedBlockNum, setPushedBlockNum] = useState(0)
  const [boardSize, setBoardSize] = useState<BoardSize>({
    sizeX: currentFirstState.sizeX,
    sizeY: currentFirstState.sizeY,
  })

  const intervalRef = useRef<number | null>(null)
  const countStart = useCallback(() => {
    if (intervalRef.current !== null) {
      return
    }
    intervalRef.current = window.setInterval(() => {
      setCount((c) => c + 1)
    }, 1000)
  }, [])
  const countStop = useCallback(() => {
    if (intervalRef.current === null) {
      return
    }
    clearInterval(intervalRef.current)
    intervalRef.current = null
  }, [])

  const setGameCompleted = () => {
    setGameState(1)
    countStop()
    setActiveTab(currentFirstState.difficulty)
    currentFirstState.difficulty !== DIFFICULTY_SPECIAL.difficulty && setShowModal(true)
    currentFirstState.difficulty !== DIFFICULTY_SPECIAL.difficulty &&
      saveCompletedResult(currentFirstState.difficulty, count)
  }
  const setGameover = () => {
    setGameState(99)
    countStop()
  }

  const checkGameStart = (): boolean => {
    if (gameState === -1) {
      setGameState(0)
      countStart()
      return true
    }
    return false
  }

  const boardStates = { gameState, board, flgPosition, count, boms, pushedBlockNum, boardSize }
  const boardFuns = {
    refreshState,
    checkGameStart,
    setGameover,
    setGameCompleted,
    setGameState,
    setPushedBlockNum,
    setFlgPosition,
    setBoard,
    setBoms,
  }

  const [showModal, setShowModal] = useState(false)
  const [activeTab, setActiveTab] = useState<Difficulty>(currentFirstState.difficulty)

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <DifficultySelector
          states={{ boardSize, boms, currentFirstState }}
          funs={{
            refreshStateWithDifficulty,
          }}
        />
        <BoardOrigin parentStates={boardStates} funs={boardFuns} />
        <HighScoreModal
          states={{ showModal, activeTab }}
          consts={{ currentDifficulty: currentFirstState.difficulty }}
          funs={{ refreshStateWithDifficulty, setShowModal, setActiveTab }}
        />
      </Main>
    </Container>
  )
}
export default Home
